version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vuexfire
    versions:
    - ">= 3.a, < 4"
  - dependency-name: core-js
    versions:
    - 3.10.2
  - dependency-name: "@nuxtjs/storybook"
    versions:
    - 4.0.0
    - 4.0.1
    - 4.0.2
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: firebase
    versions:
    - 8.3.2
    - 8.4.0
  - dependency-name: nuxt
    versions:
    - 2.15.1
    - 2.15.4
  - dependency-name: pug-code-gen
    versions:
    - 3.0.2
  - dependency-name: eslint-plugin-nuxt
    versions:
    - 2.0.0
  - dependency-name: "@storybook/addon-knobs"
    versions:
    - 6.1.18
  - dependency-name: babel-loader
    versions:
    - 8.2.2
  - dependency-name: ini
    versions:
    - 1.3.8
