

version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-{{ checksum "package.json" }}
      # install
      - run: yarn install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn lint
      - run: yarn generate-rules
      - run: yarn test
      # build
      - run: yarn build
      - run: yarn nuxt storybook build
      # deploy
      - run: bash .circleci/deploy.sh
      - store_artifacts:
          path: dist
          prefix: dist
