

version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-{{ checksum "package.json" }}
      # install
      - run: yarn global add surge
      - run: yarn install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      # build
      - run: yarn build
      # deploy
      - run: sh ./.circleci/pr_deploy.sh
      - run: sh ./.circleci/deploy.sh
      - store_artifacts:
          path: dist
          prefix: dist
